# @package _global_

model:
  name: scgpt
  pretrained_path: null
  gene_vocab_path: null
  d_model: 512
  n_layers: 12
  n_heads: 8
  max_seq_len: 1200
  n_bins: 51
  embedding_strategy: cls  # cls or mean_pool
  batch_size: 64
