defaults:
  - task: ???  # 1. Load configs/task/batch_integration.yaml
  - optional model: null     # 2. Optional foundation model (e.g. model=scgpt)
  - _self_                   # 3. Then apply any overrides from this file (if any)

hydra:
  run:
    dir: outputs/${task.name}/${task.run_group}/${task.model_name}/${now:%Y-%m-%d_%H-%M-%S}
